services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enderecos_brasil_api
    environment:
      - DATABASE_URL=postgresql://endbr_dev:endbr_dev@postgres:5432/enderecos_brasil
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: postgres:17
    container_name: enderecos_brasil_db
    environment:
      POSTGRES_USER: endbr_dev
      POSTGRES_PASSWORD: endbr_dev
      POSTGRES_DB: enderecos_brasil
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
